### ISSUE TITLE
Pilot 3 Timeline update

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-wg#108]
@laxamanaj we Should update main WG website with our new timeline for resubmission, once that is done!

![image](https://github.com/RConsortium/submissions-wg/assets/10111024/e44dd21a-bc93-4b35-8582-c6e114d31cbb)

**Comment by laxamanaj** [comment]
Sounds good, @bms63 .  Re-submission from Pilot 3 was successful on 19Apr2024.
![image](https://github.com/RConsortium/submissions-wg/assets/95468392/ef721c41-ea42-442d-8f9d-0e7801c4406b)
