### ISSUE TITLE
Create a distill website with CI/CD workflow

### ISSUE THREAD

**Issue by elong0527** [RConsortium/submissions-wg#17]
As we are using Rmd files to document everything, we may consider to transfer this repo to a distill website. 

- All Rmd will be automatically rendered. No need to save html files.
- It can enable blog as well.
- CI/CD shall also be enabled. 

reference: https://rstudio.github.io/distill/website.html

**Comment by lengning** [comment]
@brianwarner will share with us an R consortium template in several weeks. Will create a new repo under RC org including only curated information (more public friendly)

**Comment by rpodcast** [comment]
While we wait for the aforementioned R Consortium template, I'd like to get initial alignment on what information we'd like to present on the site. Here are initial thoughts from my side;
* Overview of the working group's goals
* How the group is structured (emphasizing that this is a collaborative effort across different pharma sponsors and regulators)
* Descriptions of the submission mock data sets and outputs
* Instructions on how the results were generated (direct links to the [submission-pilot1](https://github.com/RConsortium/submissions-pilot1) repo as appropriate)

**Comment by lengning** [comment]
@rpodcast sounds good to me! (feel free to make any edits, the current site was just my first attempt of `distill`)

@brianwarner just want to follow up on the r consortium template - i recall you mentioned it would be nice to follow the r consortium website template? just want to see whether the template is already available. thanks!

**Comment by lengning** [comment]
Hi @rpodcast , we will be presenting the R submission pilot at the R/pharma conference. Maybe we can target at tidying up the website before the meeting? thanks!

**Comment by lengning** [comment]
Thanks @rpodcast! I added the pilot information. feel free to make any additional edits
