### ISSUE TITLE
Create letter to FDA for pilot1

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-wg#18]
[example cover letter from Phuse](https://github.com/RConsortium/submissions-wg/blob/main/submission-package/m1/us/12-cov-let/cover.pdf)

Share purpose, scope, reviewer expectations

**reviewer exceptions based on previous discussions**

We expect the FDA reviewer to:
- reconstruct and load submitted R package(s) (non open sourced packages that submitted via eCTD)
- load open sourced packages used in this submission
- reproduce the analysis results
- share processes/steps that may be improved
- provide a written response (An example of an FDA response for a different project may be found here:  https://www.fda.gov/media/99313/download)

**Comment by elong0527** [comment]
* End of Sep: complete draft of required documents
* Mid of Oct: prepare submission to FDA.

**Comment by waddella** [comment]
please add a placeholder file to repo from #35  and paste the url into this discussion

**Comment by lengning** [comment]
working google doc: https://docs.google.com/document/d/1IhpWT_YklPbx-Un2oVYmdEbSX_avHH1LvMFP_30en0c/edit?usp=sharing
 

which contains both cover letter and adrg (#33 )
