### ISSUE TITLE
Review and finalize shell of proposed TLFs

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-wg#19]
Proposed TLFs
  - baseline: Table 14-2.01, 
  - primary analysis: Table 14-3.01, Table 14-3.02
  - figure: Figure 14-1
  - do we need a listing?
[14-2.01.pdf](https://github.com/RConsortium/submissions-wg/files/6928509/14-2.01.pdf)
[14-3.01.pdf](https://github.com/RConsortium/submissions-wg/files/6928510/14-3.01.pdf)
[14-3.02.pdf](https://github.com/RConsortium/submissions-wg/files/6928511/14-3.02.pdf)
[Figure 14-1.pdf](https://github.com/RConsortium/submissions-wg/files/6928762/Figure.14-1.pdf)

 execution plan #23

**Comment by elong0527** [comment]
All table and figure are in CDISC pilot [CSR](https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/53-clin-stud-rep/535-rep-effic-safety-stud/5351-stud-rep-contr/cdiscpilot01/cdiscpilot01.pdf)

**Comment by SHAESEN2** [comment]
Will we be using the CDISC replication effort of atorus? https://github.com/atorus-research/CDISC_pilot_replication/tree/master/outputs

**Comment by lengning** [comment]
Hi @SHAESEN2 , @elong0527 and I were thinking that for different TLFs, we may use different packages to test common packages in pharma. So I guess we will definitely leverage on existing work in the CDISC replication work, but may write a bit more codes to cover other packages not used in the replication project
