### ISSUE TITLE
Decide which packages to use for each TLF, define data sets needed

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-wg#23]
Reuse data [here](https://github.com/RConsortium/submissions-wg/tree/main/submission-package/m5/datasets/cdiscpilot01/analysis/adam/datasets), copied from [CDISC pilot](https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172)

- [14-2.01.pdf](https://github.com/RConsortium/submissions-wg/files/6928509/14-2.01.pdf)
open source packages to use: rtables
[example](https://github.com/Roche/rtables#usage)
Dataset: adsl
Roche

- [14-3.01.pdf](https://github.com/RConsortium/submissions-wg/files/6928510/14-3.01.pdf)
open source packages to use: huxtable and pharmaRTF
[reuse codes here](https://github.com/atorus-research/CDISC_pilot_replication/blob/master/programs/t-14-3-01.R)
Dataset: adadas
Atorus?

- [14-3.02.pdf](https://github.com/RConsortium/submissions-wg/files/6928511/14-3.02.pdf)
open source packages to use: r2rtf?
Dataset: adcibc
Merck

- [Figure 14-1.pdf](https://github.com/RConsortium/submissions-wg/files/6928762/Figure.14-1.pdf)
open source packages to use:
Dataset: adtte
Roche

proprietary R package to submit: an util pkg include functions like `summary_data`, `efficacy_models`, etc [here](https://github.com/atorus-research/CDISC_pilot_replication/blob/master/programs/funcs.R)

**Comment by lengning** [comment]
@elong0527 tried to populate more details on which different packages to be used for each TLF. for the first two I think we already have previous codes in a good shape. should we target using r2rtf?

**Comment by lengning** [comment]
Hi @elimillera @mstackhouse: @elong0527 and I are thinking of splitting the work among Roche, Merck and Atorus. is it ok to assign 14-3.01 to Atorus? (I think you already have all the codes - maybe just a matter of cleaning up?). Can I assign one of you to issue #27? thank you!

**Comment by mstackhouse** [comment]
@lengning sure we'd be happy to do so. And yes we do have the code. 

That said - if we're going to split this up between groups then we need to make sure that build using a consistent environment. We should have a consistent R version and set of packages used for all outputs, and that information should be delivered with the submission package.

Typically, this information is indicated in the SAP. For SAS typically just the version number is listed. We might want to think about how we want to send that information.

**Comment by elong0527** [comment]
@mstackhouse , this is an important point. 

I would suggest to use a snapshot date on MRAN (e.g. `2021-08-06`). Then all R version is defined. 

Those information shall be defined in a project specific startup file. [example](https://github.com/elong0527/esubdemo/blob/384eb636e2ca9df5d09d6cbed3a0aedca6e03386/inst/startup.R#L7). 

All R package and R package version used in the analysis shall be properly documented in ADRG before submission. 

We can further align the folder structure in #30. This is just my initial proposal: 

https://github.com/elong0527/esubdemo
