### ISSUE TITLE
Pass P21 check for all identified datasets

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-wg#29]
You can find the data here: https://github.com/RConsortium/submissions-pilot1/tree/main/adam

**Comment by elong0527** [comment]
Here is a summary information for dataset based on our initial understanding. 

We shall get confirmation if Is the SDTM, ADaM and Medra version acceptable to FDA? 

SDTM: SDTM-3.1.2
ADaM: ADaM-1.0
Medra: 8.0

Potential P21 engine: P21 2010.1

**Comment by pkwu55** [comment]
![p21_99](https://user-images.githubusercontent.com/68229647/129917067-78f31657-e6f8-44a0-85fb-535ae1aba2e1.JPG)
![p21_99_sdtm](https://user-images.githubusercontent.com/68229647/129917069-69d8c527-a64c-487f-9a59-fd2773efe712.JPG)

I ran P21 checks on both ADaM and SDTM, we have one reject in ADaM's define and one in SDTM.TS.

**Comment by mstackhouse** [comment]
We should review see if this cut of data and Define.xml is ok:
https://github.com/phuse-org/TestDataFactory/tree/main/Updated/TDF_ADaM

**Comment by pkwu55** [comment]
![image](https://user-images.githubusercontent.com/68229647/131870302-ea089491-018f-4d1b-8cef-ff47bb19e02e.png)

![image](https://user-images.githubusercontent.com/68229647/131870396-e8a184d1-930c-4185-b3a5-a0e2c5e2834f.png)

Results from TDF's cleaned-up version ADaM and SDTM, we might have to update the two define.xml for the "Invalid Standard Name" field.
