### ISSUE TITLE
Setup development repo, align on development practices

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-wg#32]
development repo: https://github.com/RConsortium/submissions-pilot1
@elong0527 @wangh107 @pkwu55 @mstackhouse @elimillera 

will follow similar structure as https://github.com/elong0527/esubdemo

(utils under R/, analytical scripts under vignette/)

coding style: tidyverse

naming: similar to https://github.com/atorus-research/CDISC_pilot_replication/tree/master/programs

**Comment by elong0527** [comment]
Could you initiate a PR from `esubdemo` to `submission-pilot1` or simply move the whole folder to `submission-pilot1`? 

I could not do it (probably because I did not have write permission)

**Comment by lengning** [comment]
done - also granted writing permission to everyone mentioned in this issue
