### ISSUE TITLE
Draft ADRG for pilot1 submission 

### ISSUE THREAD

**Issue by elong0527** [RConsortium/submissions-wg#33]
- working on google docs (Ning set it up)
 - based on Phuse ADRG template (Ning copy)
 - apply existing ADRG to the project  https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/analysis/adam/datasets/dataguide.pdf (Ning) 
 

- Update the ADRG based on R related work.

**Comment by lengning** [comment]
working google doc: https://docs.google.com/document/d/1IhpWT_YklPbx-Un2oVYmdEbSX_avHH1LvMFP_30en0c/edit?usp=sharing

which contains both cover letter and adrg
