### ISSUE TITLE
Final Review

### ISSUE THREAD

**Issue by waddella** [RConsortium/submissions-wg#52]
Last Review round before submission

**Comment by lengning** [comment]
additional reviewer (suggested by Bob : Nate Mockler (nate.mockler@biogen.com))

**Comment by Nate884** [comment]
So Ning asked me to look at the package, and throw in some comments. Feel free to take whatever you want from this, or ignore it:

**Reviewers Guide**

- There doesn't seem to be any information in the guide about the proprietary package. I know there's the roxygen comments, but I figured the reviewers would need a reference and listing of how the team validated it. (See stuff with like tplyr). Similar to documentation about SAS Macros that are sent (if there are company-wide)

**PDF Reports**
- General inconsistency with footnotes, headers, etc. Table 1 lists tlf_demographic.rmd as the program. Table 2 has "Page X of Y" while the other tables don't, and has Timestamps while the others don't, as well as <Run Interactively> as the source, so no listing as the program that generates it.
- You wouldn't call it AGEGR1 in Table 1, you'd add a label.
- KM plots are missing X and Y labels.
- Generally you put the population below the KM plot so you can see how many patients are censored. (see page 7 of this https://www.fda.gov/media/135459/download)

**Comment by Nate884** [comment]
**Following the Reviewer's Guide Guide to Installation**

- Right now you are asking them to install base R only. Is that ok, or did you want to push them to install Rstudio as well?
- Step 4 has an extra closing param:

```{r}
> install.packages(c("haven", "dplyr", "emmeans", "r2rtf","rtables", "Tplyr", "pharmaRTF", "huxtable")))
Error: unexpected ')' in "install.packages(c("haven", "dplyr", "emmeans", "r2rtf","rtables", "Tplyr", "pharmaRTF", "huxtable")))"
```
- You also need to have the user install pkglite in the previous step.

```{r}
> pkglite::unpack("r0pkgs.txt", output = ".", install = TRUE)
Error in loadNamespace(name) : there is no package called ‘pkglite’
```

- The guide says "r0pkgs.txt", but the file is "r0pkg.txt"

```{r}
> pkglite::unpack("r0pkgs.txt", output = ".", install = TRUE)

-- Unpacking from pkglite file -------------------------------------------------
-- Reading file: r0pkgs.txt ----------------------------------------------------
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'r0pkgs.txt': No such file or directory
```

- You need to have the user set the working directory **before** that step because otherwise R won't know where to grab that file.

- The assigning path step is unclear:

```{r}
> path = list(adam = ".", # Modify path to the actual location
+             path$outtable = path$outgraph = ".") # Output saved in current folder
Error: unexpected '=' in:
"path = list(adam = ".", # Modify path to the actual location
            path$outtable ="
```

(I'm assuming person in the guide is literally copy/pasting this code, since that's what we all do)

You probably want something more like:

```{r}
path = list(adam = "blahblah", outtable = ".", outgraph = ".")
```

- This sounds very dumb, but do you want the reviewers to switch the .txt file to a .R file (to take advantage of code style).
- Right now library(pilot1wrapper) is hanging on me, so I'll investigate more.

**Comment by elong0527** [comment]
Thanks Nate for the comments. Please find my response below. 

> (note from Ning: this is a response to #47 )
> 
> So Ning asked me to look at the package, and throw in some comments. Feel free to take whatever you want from this, or ignore it:
> 
> **Reviewers Guide**
> 
> * There doesn't seem to be any information in the guide about the proprietary package. I know there's the roxygen comments, but I figured the reviewers would need a reference and listing of how the team validated it. (See stuff with like tplyr https://github.com/atorus-research/Tplyr/blob/master/uat/references/output/uat.pdf). Similar to documentation about SAS Macros that are sent (if there are company-wide)

We did not perform any validation for the proprietary package at current stage. The current focus is to submit analysis code to FDA. It might depends on the organization, I would not expect validation report is a mandatory component for eCTD package. 


> **PDF Reports**
> 
> * General inconsistency with footnotes, headers, etc. Table 1 lists tlf_demographic.rmd as the program. Table 2 has "Page X of Y" while the other tables don't, and has Timestamps while the others don't, as well as  as the source, so no listing as the program that generates it.

We did not plan to achieve consistency of table/figure format in this pilot by recognizing diverse format across the industry. 

> * You wouldn't call it AGEGR1 in Table 1, you'd add a label.

Agree, the section header is updated. 
https://github.com/RConsortium/submissions-pilot1/blob/main/output/tlf-demographic.out

> * KM plots are missing X and Y labels.
> * Generally you put the population below the KM plot so you can see how many patients are censored. (see page 7 of this https://www.fda.gov/media/135459/download)

We have updated the KM plot. 
https://github.com/RConsortium/submissions-pilot1/blob/main/output/tlf-kmplot.pdf

**Comment by elong0527** [comment]
Thanks Nate. Please find my response below. 

> (note from Ning: this is a response to #47 )
> 
> **Following the Reviewer's Guide Guide to Installation**
> 
> * Right now you are asking them to install base R only. Is that ok, or did you want to push them to install Rstudio as well?
> * Step 4 has an extra closing param:

RStudio IDE is an optional item. So we did not ask reviewer to install it. 

> ```
> > install.packages(c("haven", "dplyr", "emmeans", "r2rtf","rtables", "Tplyr", "pharmaRTF", "huxtable")))
> Error: unexpected ')' in "install.packages(c("haven", "dplyr", "emmeans", "r2rtf","rtables", "Tplyr", "pharmaRTF", "huxtable")))"
> ```

Updated in ADRG. 

> 
> * You also need to have the user install pkglite in the previous step.
> 
> ```
> > pkglite::unpack("r0pkgs.txt", output = ".", install = TRUE)
> Error in loadNamespace(name) : there is no package called ‘pkglite’
> ```

Agree, we have added `pkglite` in ADRG. 

> 
> * The guide says "r0pkgs.txt", but the file is "r0pkg.txt"
> 
> ```
> > pkglite::unpack("r0pkgs.txt", output = ".", install = TRUE)
> 
> -- Unpacking from pkglite file -------------------------------------------------
> -- Reading file: r0pkgs.txt ----------------------------------------------------
> Error in file(con, "r") : cannot open the connection
> In addition: Warning message:
> In file(con, "r") :
>   cannot open file 'r0pkgs.txt': No such file or directory
> ```
> 

We have fixed this in the ADRG. 

> * You need to have the user set the working directory **before** that step because otherwise R won't know where to grab that file.

In step 1 of the ADRG, we clarified working directory. " All steps below should be executed in this working directory represented as "." in the example R code below." 

If this is unclear, could you propose a sentence? Thanks! 


> * The assigning path step is unclear:
> 
> ```
> > path = list(adam = ".", # Modify path to the actual location
> +             path$outtable = path$outgraph = ".") # Output saved in current folder
> Error: unexpected '=' in:
> "path = list(adam = ".", # Modify path to the actual location
>             path$outtable ="
> ```
> 
> (I'm assuming person in the guide is literally copy/pasting this code, since that's what we all do)
> 
> You probably want something more like:
> 
> ```
> path = list(adam = "blahblah", outtable = ".", outgraph = ".")
> ```

Updated in ADRG.

> * This sounds very dumb, but do you want the reviewers to switch the .txt file to a .R file (to take advantage of code style).

eCTD require all filename in lower cases, now we use `.r` as file extension. 

> * Right now library(pilot1wrapper) is hanging on me, so I'll investigate more.

Please let us know if you find any further issue. Thanks!
