### ISSUE TITLE
Standalone information sharing meetings to share each pharma company's internal R strategy/progress on filing

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-wg#55]
We will start one or a series of small group meetings to share each pharma company's internal R strategy/progress on regulatory submission. The first meeting will be hosted in Jan.

Current participants:
Roche (Ning)
J&J (Heidi)
Merck (Yilong)

If you are interested in attending, please reply or contact me. Thank you!

**Comment by NNaikp** [comment]
I would also like to join!
Novo Nordisk (Ari)

**Comment by NNaikp** [comment]
@lengning If you need any help with setting this up, then please let me know. Would be happy to help :)

**Comment by rpodcast** [comment]
I'd be glad to join this discussion!

**Comment by lengning** [comment]
Hi @NNaikp , would you mind sharing with me your email address? thank you

**Comment by NNaikp** [comment]
@lengning it's aikp@novonordisk.com
