### ISSUE TITLE
Shiny app as a package for second submission

### ISSUE THREAD

**Issue by rpodcast** [RConsortium/submissions-wg#57]
After our recent meeting (2022-01-07), the group expressed interest in creating a Shiny application bundled as an R package to test out a new submission, based upon the data and results of the first submission. Initial tasks / requests as we begin to scope out the details:
* [ ] Create a new repository for the second submission pilot
* [ ] Anyone who wishes to participate in this second pilot, please respond to this issue or contact @rpodcast 
* [ ] Create dedicated issues for the key tasks of the pilot

**Comment by NNaikp** [comment]
I would very much like to participate 😃 

Are there any discussions on re-using the first submission to also get other agencies than FDA on-board? Maybe including a first submission to PMDA as a parallel track? Or reaching out to EMA who have expressed that they would require data submissions in the near future?

**Comment by lengning** [comment]
just created the pilot2 dev repo: https://github.com/RConsortium/submissions-pilot2

**Comment by sclewis23** [comment]
Hi Team - I attended the working group meeting today (I was driving so wasn't able to respond on the call), it was my first time attending.  Great to hear all the exciting plans this working group is coming up with.
My is question about the second submission (pilot 2), why would we want to wait for the approval(release) of the teal R package, which could be 3 months (for legal approval)?  
Seems like a long time to wait, when we are just trying to trying submit a simple shiny app based off of pilot-1's data transformations.
This also restricts the support for other team members on the development of the Shiny app or testing of the installation/setup instructions for the reviewer (prior to the approval of the teal R package).
I'm not sure if this was discussed previously, if it was please let me know which thread/issue/video to review.
Thanks
