### ISSUE TITLE
[volunteers needed] Review/reproduce updated pilot 1 submission package

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-wg#61]
Looking for volunteers to review updated pilot 1 submission package. This is in response to the FDA [summary letter](https://github.com/RConsortium/submissions-wg/blob/main/Documents/Summary_R_Pilot_Submission.pdf)

Review by Jan 24 (Mon) is preferred

Todo
- Review [Response Letter to FDA](https://github.com/RConsortium/submissions-pilot1-to-fda/blob/main/m1/us/response-to-fda-1.pdf)
- Rerun R codes, following the appendix of [ADRG](https://github.com/RConsortium/submissions-pilot1-to-fda/blob/main/m5/datasets/rconsortiumpilot1/analysis/adam/datasets/adrg.pdf), compare results to outputs in the [report](https://github.com/RConsortium/submissions-pilot1-to-fda/blob/main/m1/us/report-tlf.pdf). Make sure the numbers are reproducible and FDA comments are addressed

Please reply to this issue if you would like to help with the review. Thank you!!

**Comment by elong0527** [comment]
After all review completed, we need to update the report-tlf (because of time stamp change)

https://github.com/RConsortium/submissions-pilot1-to-fda/blob/main/m1/us/report-tlf.pdf

Also suggest to remove the "Version Jan 18th 2022" as it may mismatch with the table time stamp.

**Comment by elong0527** [comment]
In Response letter to FDA, I would suggest to state below for rounding issue. 

We agree that the slight differences are likely to happen when different operating system is used.

**Comment by SHAESEN2** [comment]
Hey @lengning I would like to help to address the comments.

**Comment by sclewis23** [comment]
Hey @lengning ,
I was able to rerun the outputs and confirm the same results as in the report-tlf.pdf
I used a window machine and didn't see any rounding differences.
Do we have any other information to compare sessionInfo or system environment to ensure it is a rounding error?

But I did get one warning and three errors not able to find pdf files:
Warning message:
In as.POSIXlt.POSIXct(x, tz) : unable to identify current timezone 'C':
please set environment variable 'TZ'

Error in knitr::include_graphics("pdf/tlf-efficacy.pdf") : 
  Cannot find the file(s): "pdf/tlf-efficacy.pdf"
Error in knitr::include_graphics("pdf/tlf-kmplot.pdf") : 
  Cannot find the file(s): "pdf/tlf-kmplot.pdf"
Error in knitr::include_graphics("pdf/tlf-primary.pdf") : 
  Cannot find the file(s): "pdf/tlf-primary.pdf"

TZ wasn't set in my test environment.

I assume these knitr errors are expected?

`
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] pharmaRTF_0.1.3      huxtable_5.4.0       Tplyr_0.4.1          tidyr_1.1.3          visR_0.2.0           cowplot_1.1.1        ggplot2_3.3.5        emmeans_1.6.3        r2rtf_0.3.0          pilot1wrappers_0.1.1 rtables_0.3.8       
[12] magrittr_2.0.1       dplyr_1.0.7          haven_2.4.3         

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.1 xfun_0.25        remotes_2.4.0    purrr_0.3.4      lattice_0.20-45  splines_4.1.2    colorspace_2.0-2 vctrs_0.3.8      generics_0.1.0   htmltools_0.5.2  yaml_2.2.1       survival_3.2-13  utf8_1.2.2       rlang_0.4.11    
[15] pillar_1.6.2     withr_2.4.2      glue_1.4.2       lifecycle_1.0.0  plyr_1.8.6       stringr_1.4.0    munsell_0.5.0    gtable_0.3.0     mvtnorm_1.1-2    evaluate_0.14    knitr_1.33       forcats_0.5.1    tzdb_0.1.2       fastmap_1.1.0   
[29] fansi_0.5.0      Rcpp_1.0.7       xtable_1.8-4     readr_2.0.1      renv_0.14.0      scales_1.1.1     farver_2.1.0     hms_1.1.0        digest_0.6.27    stringi_1.7.4    grid_4.1.2       cli_3.0.1        tools_4.1.2      pkglite_0.2.0   
[43] tibble_3.1.4     crayon_1.4.1     pkgconfig_2.0.3  Matrix_1.3-4     ellipsis_0.3.2   estimability_1.3 assertthat_0.2.1 rmarkdown_2.10   rstudioapi_0.13  R6_2.5.1         compiler_4.1.2  
`

**Comment by elong0527** [comment]
Thanks @sclewis23 for rerunning the analysis. I have removed the `pdf` related part in the submission package. 

Just to confirm, the rerun use the submission code and follow ADRG folder. 

https://github.com/RConsortium/submissions-pilot1-to-fda/blob/main/m5/datasets/rconsortiumpilot1/analysis/adam/datasets/adrg.pdf

https://github.com/RConsortium/submissions-pilot1-to-fda/tree/main/m5/datasets/rconsortiumpilot1/analysis/adam/programs

**Comment by NNaikp** [comment]
Hi @lengning & @elong0527!

I was able to re-produce the results based on the steps in the ADRG 👍 
A few things I was thinking while I was following the steps:

- setwd() is mentioned but not given as code. I did write setwd() when following that step.
- I had an active .Rprofile while going through the installation of r0pkg which gave some odd messages. Might be alright.
- The path example given does not contain "output" in the list of paths, so if you like me copy that and update the adam path you will get weird messages until you figure that out. To avoid any confusion I would just put `output = "."` instead of `outtable = ".", outgraph = "."` since it is repeated both in the ADRG and in every header.
- In tlf-primary.r the last hf_line for the technical footnote yielded date/time in local language and not english. Again maybe just my machine (windows with local R 4.1.2).

Other stuff:

- In ADRG 7.3 all programs have file extension .txt but in /programs folder files have .r.
- pilot1wrappers NEWS.md has double 0.1.0 news
- pilot1wrappers::eff_models.R mentions ARM [here](https://github.com/RConsortium/submissions-pilot1-to-fda/blob/799f95ae19eb9396010e332afd6bccee6ec64e6b/m5/datasets/rconsortiumpilot1/analysis/adam/programs/r0pkg.txt#L219) and [here](https://github.com/RConsortium/submissions-pilot1-to-fda/blob/799f95ae19eb9396010e332afd6bccee6ec64e6b/m5/datasets/rconsortiumpilot1/analysis/adam/programs/r0pkg.txt#L263) but there is no ARM included in the define.xml in the submission package. Maybe just a reference to the original CDISC package?
- In report-tlf.pdf:
    - treatment/column ordering is not consistent
    - Title of Table 14-3.02 does not match content - parameter is Glucose (mmol/L) not CIBIC+ and data is from baseline and week 20 not 24.
    - Treatment in 14-3.02 is now 'Study Drug' instead of Xan High Dose - I don't know if that is on purpose?

**Comment by elong0527** [comment]
Thanks @NNaikp for the detail review. I have re-direct them to separate issues or PRs to address them. 

> setwd() is mentioned but not given as code. I did write setwd() when following that step.

Could you specify the location that we mention `setwd()`?

> I had an active .Rprofile while going through the installation of r0pkg which gave some odd messages. Might be alright.

Please share the message in a separate issue. 

>The path example given does not contain "output" in the list of paths, so if you like me copy that and update the adam path you will get weird messages until you figure that out. To avoid any confusion I would just put output = "." instead of outtable = ".", outgraph = "." since it is repeated both in the ADRG and in every header.

Agree. Will update in ADRG and submission program. Refer https://github.com/RConsortium/submissions-pilot1-to-fda/issues/7

> In tlf-primary.r the last hf_line for the technical footnote yielded date/time in local language and not english. Again maybe just my machine (windows with local R 4.1.2).

Refer https://github.com/RConsortium/submissions-pilot1/pull/19#issuecomment-1019007507

Other stuff:

> In ADRG 7.3 all programs have file extension .txt but in /programs folder files have .r.

Addressed in ADRG draft. Will update pdf file. 

> pilot1wrappers NEWS.md has double 0.1.0 news

Addressed in https://github.com/RConsortium/submissions-pilot1/commit/4bf431f2a172f4e91e902bca235c8cad6f9c7884

>pilot1wrappers::eff_models.R mentions ARM here and here but there is no ARM included in the define.xml in the submission package. Maybe just a reference to the original CDISC package?

Refer https://github.com/RConsortium/submissions-pilot1/pull/19#issuecomment-1019007507

In report-tlf.pdf:

> treatment/column ordering is not consistent

Refer https://github.com/RConsortium/submissions-pilot1/pull/19#issuecomment-1019007507

> Title of Table 14-3.02 does not match content - parameter is Glucose (mmol/L) not CIBIC+ and data is from baseline and week 20 not 24.

Refer https://github.com/RConsortium/submissions-pilot1-to-fda/issues/8

> Treatment in 14-3.02 is now 'Study Drug' instead of Xan High Dose - I don't know if that is on purpose?

Addressed in https://github.com/RConsortium/submissions-pilot1/commit/4bf431f2a172f4e91e902bca235c8cad6f9c7884

**Comment by NNaikp** [comment]
Hi @elong0527.
For the comment about working directory I'm referring to this section in the ADRG:

![image](https://user-images.githubusercontent.com/85683724/151056153-89ca6e97-682a-4681-a400-afa64910ba12.png)

In my mind it would make sense to get the reviewer to use `setwd("C:/tempwork")` here. What do you think?
I will see if I can re-create the installation notes of r0pkg and create a new issue.

**Comment by elong0527** [comment]
Thanks @NNaikp for the clarification. 

I assume the reviewer has basic R knowledge and know how to set up working directory (or simply google it).

I assume most user can install the binary package from Windows. For this first pilot, we did not touch `Rtools` part. For future pilot, we may need it clarify it.

**Comment by lengning** [comment]
Hi all, Hye Soo shared her code in [this issue](https://github.com/RConsortium/submissions-pilot1-to-fda/issues/10)

It would be appreciated if you can try running it on your operating system, to investigate the rounding difference a bit further

**Comment by lengning** [comment]
v0.1.1 finalized: https://github.com/RConsortium/submissions-pilot1-to-fda/releases/tag/v0.1.1

Thanks everyone!
