### ISSUE TITLE
conference presentions

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-wg#73]
- [x]  rstudio conference
- [x] sdss
- [x] useR
- [x] FDA workshop poster
- [ ] phuse
- [ ] pharmaSUG
- [x] DIA 
- [x] Rpharma
- [ ] PSI

please reply if there are other conferences we want to target

Confirmed talks:

- [DIA/FDA Biostatistics Industry and Regulator Forum](https://www.diaglobal.org/Tools/Content.aspx?type=eopdf&file=%2fproductfiles%2f9891829%2f22008-program%2Epdf) : : DIA Data Science and Statistics Community Meeting Discussion: Yes, You Can Use R in Regulatory Submissions (Ning and Coline from Roche)
- SDSS: Data-driven Healthcare on 6/9/2022 from 1:15 PM to 2:45 PM Eastern (Ning?)
- UseR
- ASA biopharma FDA/industry workshop

**Comment by NNaikp** [comment]
Do we not want to target conferences like PHUSE and PharmaSUG as well?

**Comment by elong0527** [comment]
FDA workshop is calling for poster https://ww2.amstat.org/meetings/biop/2022/submitanabstract.cfm

**Comment by lengning** [comment]
thanks both! it seems we may missed the deadline for pharmasug and phuse US connect?

btw i am happy to do the abstract submissions. if we got selected in multiple conferences i hope we can divide the conquer in presenting :)

**Comment by NNaikp** [comment]
Well, @mstackhouse is the stream chair for the open-source stream at PHUSE US Connect - maybe he can tell us whether the stream is full? 😄

**Comment by mstackhouse** [comment]
@lengning  and @NNaikp  PHUSE call for papers is closed for 2022 unfortunately. Pharmasug closed in January.

[PHUSE EU Call for papers](https://www.phuse-events.org/attend/frontend/reg/tAbsSubmitterLogin.csp?pageID=8009&eventID=16) is open if we want to shoot for Europe.

**Comment by NNaikp** [comment]
I can send something for the PHUSE EU Connect. But how does it usually work?
Is it an update from the WG or is your/my own take on things + maybe my company's? :)

**Comment by lengning** [comment]
@NNaikp I have been submitting abstracts on behalf of the WG. You are welcome to phrase it as sth from your personal/company perspective as well!

The UseR abstract can be found [here](https://user2022.r-project.org/program/talks/#session-10-building-the-r-community-1)

**Comment by NNaikp** [comment]
@lengning thanks for the quick reply!
I would prefer to promote the WG :)

Does anybody need to approve it?

**Comment by lengning** [comment]
no approval needed :) go ahead! would be nice to share the presentation materials with the WG to collect feedback before the presentation

**Comment by NNaikp** [comment]
Great! This also gives me an opportunity to try and host some xaringan slides on GitHub 🤖
