### ISSUE TITLE
[seek review] slide deck and poster for SDSS

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-wg#82]
Please leave your feedback by May31. Thank you!
[R submission Pilots to FDA - SDSS presentation.pdf](https://github.com/RConsortium/submissions-wg/files/8765084/R.submission.Pilots.to.FDA.-.SDSS.presentation.pdf)
[SDSS poster - r submission.pdf](https://github.com/RConsortium/submissions-wg/files/8765085/SDSS.poster.-.r.submission.pdf)

**Comment by AppSecAntibody** [comment]
The poster reads "Roche-Genentech (we are hiring!)". Is that an error ?
