### ISSUE TITLE
NN x Posit Webinar

### ISSUE THREAD

**Issue by NNaikp** [RConsortium/submissions-wg#91]
Hi all,
Just happened to stumble upon the minutes from last weeks meeting and saw/heard you guys talking about the upcoming webinar!

The submission is just a regular old NDA submission, no fast track, no special regulation (Novo Nordisk does not develop vaccines).
It includes clinpharm, phase2/3, integrated summaries and all that. Also some ADaM datasets were developed in R. 

It is built upon the efforts made here in this WG from the pilot 1 submission - so without that as I starting point we would have been lost! 🚀 

Doing the pilot 1 approach in real life turned out to have WAY more complexity as we were sending a submission developed in an enterprise grade linux based system with multiple internal packages and RSPMs to statistical reviewers running R on windows based local PCs using CRAN.

Recently, I've started to use the story about the three little pigs as an analogy for these submission strategies.
The pilot 1 was the one made of straw. The NN one is probably the one made of wood. The one you are working on now with a container is probably the one made of stone (or even steel) and where we really want to go.

But without the work done here and the involvement of FDA, I don't think we would have dared to take it this far.

**So thank you so much for all the efforts you've made!**

We are planning to return a lot of all of these learnings back to the community - both through Posit, Rconsortium, PHUSE and pharmaverse.

**Comment by lengning** [comment]
thanks a lot for the detailed info!! look forward to learning more!

**Comment by lengning** [comment]
thanks a lot for the detailed info!! look forward to learning more!

**Comment by elong0527** [comment]
Wow! Congratulations! Looking forward to hearing more!!

**Comment by nanxstats** [comment]
Awesome! It's always a pleasure to hear positive feedback about cross-industry collaborations and I do want to give a big shout out to Ning and Yilong for their substantial contributions which made Pilot 1 a reality. I also look forward to the future submission pilots from this working group and the development happening in other organizations. 🤗
