### ISSUE TITLE
Retire old website

### ISSUE THREAD

**Issue by stevegbrooks** [RConsortium/submissions-wg#92]
Hi team,

If you search for "R for submission RConsortium", the first result is a website that seems like its no longer maintained. 

https://rconsortium.github.io/r-submission-site/wg.html

I had to do some digging to find the "real" website here: https://rconsortium.github.io/submissions-wg/

I suggest the team retires the website at the first link in favor of the second so people don't get the wrong impression.

Thanks

Steve

**Comment by bms63** [comment]
I'm very much in favor of this!!  Should we kill the site or put a redirect to the new site?

**Comment by stevegbrooks** [comment]
a redirect seems like a graceful way to do it for now :)

**Comment by rpodcast** [comment]
I completely forgot that this previous site existed! The site originates from the [r-submission-site](https://github.com/RConsortium/r-submission-site)I repository, and I just switched the setting to un-published in the repository settings (I didn't see a clever way to do a re-direct). 

I'll add a quick README to that repository that points to the proper submissions working group site repository. Then I'll archive the repository.

**Comment by rpodcast** [comment]
The repository has been archived with the [README](https://github.com/RConsortium/r-submission-site/blob/main/README.md) pointing to the proper repository.
